services:
  gateway:
    image: gateway
    ports:
      - 8080:8080
    networks:
      - eureka-net


  eureka-service:
    image: eureka-service
    networks:
      - eureka-net

  user-service:
    image: user-service
    depends_on:
      - user-service-db
    networks:
      - eureka-net
      - user-service-net

  user-service-db:
    image: postgres
    ports:
      - 5544:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-service
    networks:
      - user-service-net

  example-service:
    image: example-service
    depends_on:
      - example-service-db
    networks:
      - eureka-net
      - example-service-net

  example-service-db:
    image: postgres
    ports:
      - 5545:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example-service
    networks:
      - example-service-net
  redis:
    image: redis
    ports:
      - 5546:6379
    networks:
      - redis-net

networks:
  eureka-net:
  redis-net:
  user-service-net:
  example-service-net: