services:
  user-service-db:
    image: postgres
    ports:
      - 5544:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-service
  example-service-db:
    image: postgres
    ports:
      - 5545:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example-service
  redis:
    image: redis
    ports:
      - 5546:6379