services:
  user-service-db:
    image: postgres
    ports:
      - 5544:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user-service
