spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: example-service
          uri: lb://EXAMPLE-SERVICE
          predicates:
            - Path=/example-service/api/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/api/**
          filters:
            - StripPrefix=1

server:
  port: 8080
